### ISSUE TITLE
Import wildcard

### ISSUE THREAD

**Issue by dhvcc** [timoniq/vkbottle-types#14]
https://github.com/timoniq/vkbottle-types/blob/b1710398e49c55995bcf5aeb76c3704213369de4/vkbottle_types/events/__init__.py#L3 Тут и в паре других мест есть wildcard импорты, это нехорошо как для линтинга, так и для разработчиков. Надо бы экспортировать модуль, а не все данные из него

**Comment by ScriptHound** [comment]
Линтинг не используется по причине кодогенерации. Код вктайпов никто руками не пишет.

**Comment by dhvcc** [comment]
Значит стоит обновить кодген, что, что бы импортировать модуль, это сильно затруднительно? 

Код руками не пишут, но поправляют и читают, поэтому это всё ещё имеет эффект.

**Comment by ScriptHound** [comment]
Импортирование жестко заданных модулей может усложнить написание кодогенерации, поскольку импорты могут в каждом файле быть разными. Читать там в принципе особо нечего, поскольку код шаблонный и большинство классов содержат в себе только переменные, либо однообразные методы.
